/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "/s": "/秒",
    "Clear": "清除",
    "Compact fully upgraded": "紧凑型全面升级",
    "Crafting": "制作",
    "Foundries": "铸造厂",
    "Mana": "法力",
    "Generation": "生成",
    "Sort": "排序",
    "Speed": "速度",
    "Yield": "生产",
    "• No bonuses": "• 无加成",
    "Base time:": "基础时间:",
    "crafting T": "制作 T",
    "Effective:": "效率:",
    "foundry": "铸造厂",
    "Gem": "宝石",
    "Gems": "宝石",
    "Idle": "空闲",
    "Impact (": "影响 (",
    "mana to unlock": "法力去解锁",
    "Prisms": "棱镜",
    "Select Recipe": "选择配方",
    "Requires": "要求",
    "Speed: ×": "速度: ×",
    "Stop Production": "停止生产",
    "Upgrade": "升级",
    "Yield: ×": "生产: ×",
    "Tip: right click to set recipe for all slots. Right clicking on a crafting slot clears it.": "提示：右键单击可以设置所有槽的配方。右键点击一个制作槽可以清除它。",
    "Community": "社区",
    "Copy to Clipboard": "复制到剪贴板",
    "Danger Zone": "危险区",
    "Display Settings": "显示设置",
    "Export Save": "导出存档",
    "Download File": "下载文件",
    "Hard Reset": "硬重置",
    "Import Save": "导入存档",
    "Imported from file": "已导入文件",
    "Join Discord": "加入 Discord",
    "Load File": "从文件导入",
    "Numbers above this value will display in scientific notation.": "高于此值的数字将以科学记数法显示。",
    "Paste from Clipboard": "从剪切板粘贴",
    "Preview:": "预览:",
    "Scientific Notation Threshold": "科学记数法阈值",
    "This will permanently delete all progress.": "这将永久删除所有进度。",
    "Artifacts": "神器",
    "• Prisms: ×": "• 棱镜: ×",
    "• Speed: ×": "• 速度: ×",
    "• Upgrades: ×": "• 升级: ×",
    "• Yield: ×": "• 生产: ×",
    "Affects: T": "影响: T",
    "Basic Prism": "基础棱镜",
    "chunks": "块",
    "Cost per chunk:": "成本每块:",
    "Cost:": "成本:",
    "deficit will increase": "赤字将会增加",
    "foundries": "铸造厂",
    "gems": "宝石",
    "Hide crafted": "隐藏已制作",
    "Progress:": "进度:",
    "When complete:": "当完成:",
    "Attack": "攻击",
    "No foundries crafting T": "没有铸造厂在制造 T",
    "Attack Speed": "攻击速度",
    "Combat": "战斗",
    "Combat Upgrades": "战斗升级",
    "Core Upgrades": "核心升级",
    "Energy Cores": "能量核心",
    "Damage": "伤害",
    "Damage:": "伤害:",
    "Enemy #": "敌人 #",
    "Crafting Slot": "制作槽位",
    "Energy Cores": "能量核心",
    "Faster Revive": "更快的复活",
    "Health": "生命值",
    "HP": "生命值",
    "Highest Enemy": "敌人最高记录",
    "Mana Boost": "法力提升",
    "Speed:": "速度:",
    "VS": "VS",
    "You": "你",
    "Craft Speed": "制作速度",
    "Core Upgrades": "核心升级",
    "DEFEATED": "被击败了",
    "Reviving in...": "复活中...",
    "• Global: ×": "• 全局: ×",
    "Combat Artifacts": "战斗神器",
    "attack speed": "攻击速度",
    "Cost per cycle:": "每循环成本:",
    "cycles": "循环",
    "HP/s regen": "生命值/秒 回复",
    "max HP": "最大生命值",
    "Combat bonuses:": "战斗加成:",
    "HP/s": "生命值/秒",
    "speed": "速度",
    "Exported to clipboard": "已导出到剪贴板",
    "MAX": "满级",
    "Pulverizer": "粉碎机",
    "(CAPPED)": "(上限)",
    "Auto Combat": "自动战斗",
    "Current Mana": "当前法力",
    "Base SP": "基础奇点点数",
    "Next Milestone": "下一个里程碑",
    "Hide completed": "隐藏已完成",
    "Singularity Points": "奇点点数",
    "SP": "奇点点数",
    "SP Calculation": "奇点点数计算",
    "Skill Tree": "技能树",
    "Singularity": "奇点",
    "Singularities": "奇点",
    "Total": "总计",
    "Unlock Mastery": "解锁精通",
    "Unlocks the Mastery system": "解锁精通系统",
    "What Persists": "什么会持续存在",
    "What Resets": "什么会重置",
    "Perform Singularity": "执行奇点",
    "• All gem upgrades (Speed/Yield)": "• 所有宝石升级（速度/产量）",
    "• All skill tree purchases": "• 所有技能树购买",
    "• Artifacts (except kept by Artifact Memory)": "• 神器（被神器记忆保存的除外）",
    "• Combat progress and upgrades": "• 战斗进度和升级",
    "• Foundry count (resets to 1 + extra slots)": "• 铸造厂数量（重置为 1 + 额外槽位）",
    "• Mana and all gems": "• 法力和所有宝石",
    "• Mastery (shards and levels)": "• 精通（碎片和等级）",
    "• Milestone unlocks": "• 里程碑解锁",
    "• Prisms (except kept by Prism Memory)": "• 棱镜（棱镜存储器保存除外）",
    "• Singularity Points (SP)": "• 奇点点数（SP）",
    "• Tab unlocks": "• 选项卡解锁",
    "Auto-unlock & upgrades": "自动解锁和升级",
    "Automatically buys Speed and Yield upgrades for T1 and T2 gems when you can afford them, without spending mana.": "自动购买速度和产量升级T1和T2宝石时，你可以负担得起他们，不消耗法力。",
    "Automatically buys Speed and Yield upgrades for T3 and T4 gems when you can afford them, without spending mana.": "自动购买速度和产量升级T3和T4宝石时，你可以负担得起，不消耗法力。",
    "Automatically unlocks combat (spends 20T mana) and auto-buys combat upgrades (HP, Damage, Attack Speed, Revive Speed) when you can afford them, without spending mana.": "自动解锁战斗（花费20T法力值）和自动购买战斗升级（HP，伤害，攻速，复活速度），当你能负担的时候，不消耗法力值。",
    "Mastery lets you collect shards from gem crafting to gain permanent bonuses.": "精通可以让你从宝石制作中收集碎片来获得永久奖励。",
    "more for": "更多关于",
    "Perform your first singularity to unlock": "执行你的第一个奇点来解锁",
    "Perform your first singularity to unlock the skill tree.": "执行你的第一个奇点来解锁技能树。",
    "(You have": "(你有",
    "Next:": "下一个:",
    "Mastery": "精通",
    "damage": "伤害",
    "Current:": "当前:",
    "Combat Mastery": "战斗精通",
    "Level:": "等级:",
    "mana": "法力",
    "Mana is no longer capped at 1e27. Gain more SP per singularity based on how far past the cap you go.": "法力不再上限为1e27。每个奇点获得更多的奇点点数取决于你超过上限的距离。",
    "Prism Memory": "棱镜存储",
    "Prism Power": "棱镜力量",
    "Remove 1e27 mana cap": "移除 1e27 法力上限",
    "Speed Boost (free)": "速度提升 (免费)",
    "✓ Maxed": "✓ 最大",
    "Gem Mastery": "宝石精通",
    "Keep highest tier artifact per level": "每级保留最高层级的神器",
    "Keep highest tier prism per level": "每级保留最高层级的棱镜",
    "Foundry Expansion": "铸造厂扩建",
    "Artifact Memory": "神器存储",
    "Break Singularity": "打破奇点",
    "Click nodes adjacent to owned nodes to purchase. Drag to pan. All bonuses persist through resets.": "点击与已拥有节点相邻的节点进行购买。拖动以移动。所有的奖励通过重置持续存在。",
    "+0.1x prism effectiveness per level (additive)": "每级+0.1x棱镜效率（加法）",
    "+1 starting foundry slot per level": "每级+1铸造厂槽位",
    "+2 max level for gem speed/yield upgrades per level": "每级+2宝石速度/产量升级等级上限",
    "| Chance:": "| 几率:",
    "| Rolls:": "| 重掷:",
    "% speed, +": "% 速度, +",
    "% yield": "% 产量",
    "Current: +": "当前: +",
    "Energy Core Drops": "能量核心掉落",
    "From": "从",
    "Level": "等级",
    "Level Bonus": "等级加成",
    "Shard Log": "碎片日志",
    "Character Locked": "角色未解锁",
    "Unlock Combat": "解锁战斗",
    "Global Yield": "全局生产",
    "Global Speed": "全局速度",
    "How It Works": "工作原理",
    "Artifact Effectiveness": "神器效果",
    "Shards": "碎片",
    "shards = level up": "碎片 = 升级",
    "Speed Bonus": "速度加成",
    "Total:": "总计:",
    "Yield Bonus": "生产加成",
    "Mastery Bonuses": "精通加成",
    "per craft": "每次制作",
    "No shards found yet...": "暂未发现碎片...",
    "Prism Effectiveness": "棱镜效果",
    "• Each shard: +": "• 每个碎片: +",
    "• Each tier has a unique level bonus": "• 每层都有一个独特的等级奖励",
    "• Mastery persists through resets": "• 精通通过重置持续存在",
    "• Each gem craft has a chance to drop a shard": "• 每个宝石制作有几率掉落一个碎片",
    "• Drop rate scales with level (see tier cards)": "• 掉落率随等级变化（参见层级卡片）",
    "chance)": "几率)",
    "Combat Veteran": "战斗老兵",
    "Bonus Cores": "奖励核心",
    "Mana Bonus (": "法力加成 (",
    "Merge": "合并",
    "rolls": "重掷之后",
    "SP Boost": "奇点点数提升",
    "will go negative!": "将会变成负数！",
    "Merge Grid Size": "合并网格大小",
    "Ascension": "转生",
    "after": "在",
    "+0.5x energy core drops per level (additive)": "每级+0.5x能量核心掉落（添加）",
    "+1 max level for combat mana upgrades per level": "每级+1战斗法力升级上限",
    "+1 merge grid row and column per level": "每级+1合并网格行和列",
    "+5 combat upgrade caps": "+5战斗升级上限",
    "+50% SP gain": "+50% 奇点点数增益",
    "All singularity point gains are increased by 50%.": "所有奇点点数增益增加50%。",
    "Raises maximum level for HP, Damage, and Attack Speed by 5. Revive Speed caps at 15 (instant revive).": "提高生命值，攻击力和攻速的最高等级5。恢复速度上限为15（即时恢复）。",
    "Spawn Log": "生成日志",
    "Prism": "棱镜",
    "No gems spawned yet": "暂无已生成宝石",
    "Merge Bonuses": "合并加成",
    "Lv": "等级",
    "Delete Gem": "删除宝石",
    "Grid persists through Singularity. Gem cost resets.": "网格通过奇点持续存在。宝石成本重置。",
    "Delete Gem": "删除宝石",
    "Buy Random Gem": "购买随机宝石",
    "Buy random gems to fill the grid. Identical gems auto-merge into higher levels.": "购买随机宝石来填满格子。相同的宝石自动合并到更高的等级。",
    "Confirm Delete": "确认删除",
    "Click a gem to delete": "点击一个宝石以删除",
    "Required:": "要求:",
    "to Universe": "到宇宙",
    "Universe": "宇宙",
    "You may": "你可以",
    "features are coming soon...": "功能即将推出...",
    "Current Mana:": "当前法力:",
    "Ascend": "转生",
    ", discovering new challenges and features beyond this reality.": "发现超越现实的新挑战和新特征。",
    "Ascending now will prepare your save for future content.": "现在转生将为将来的内容准备你的保存。",
    "Warning: Ascending will reset ALL progress. Your gems, foundries, upgrades, prisms, combat, singularity, mastery, and merge progress will be lost.": "警告：转生将重置所有进度。你的宝石、铸造厂、升级、棱镜、战斗、奇点、精通和合并进程将会丢失。",
    "You have reached the pinnacle of Universe": "你已经到达了宇宙的巅峰",
    "Dust": "魔尘",
    "Enchanting": "附魔",
    "Pulverizers": "粉碎机",
    "Cost per craft:": "每次制作成本:",
    "Produces:": "生产:",
    "Select Pulverizer Recipe": "选择粉碎配方",
    "applied": "已应用",
    "Current": "当前",
    "Discount": "折扣",
    "Enchant": "附魔",
    "enchantment": "附魔",
    "Enchanting cost:": "附魔成本:",
    "Next": "下一级",
    "Strength": "力量",
    "Tier": "层级",
    "Select gem tier to enchant": "选择要附魔的宝石层级",
    "Reduces the gem cost to craft this tier. Shows cost as % of original.": "减少制造这个层级所需的宝石。显示成本为原价的%。",
    "Increases the mana bonus provided by this gem tier.": "增加这个宝石层级提供的法力加成。",
    "Increases crafting speed for this gem tier.": "提升本层级宝石的制造速度。",
    "Swift Crafting": "快速制作",
    "Reset": "重置",
    "All crafting speed is doubled.": "所有制造速度加倍。",
    "Bonus SP": "奖励奇点点数",
    "Bonus SP (Lv": "奖励奇点点数 (等级",
    "Lv.": "等级",
    "Remove 1e21 mana cap": "移除 1e21 法力上限",
    "Dust Speed": "魔尘速度",
    "Dust yield: ×": "魔尘生产: ×",
    "Dust Upgrades": "魔尘升级",
    "Dust Yield": "魔尘生产",
    "Dust Damage": "魔尘伤害",
    "Dust Cost": "魔尘成本",
    "Disabled": "禁用",
    "Core Automation": "核心自动化",
    "Enabled": "启用",
    "Copy to All": "复制到全部",
    "Ascension Bonus": "转生加成",
    "Automation": "自动化",
    "enchants)": "附魔)",
    "enchantment power": "附魔力量",
    "Enchant Automation": "附魔自动化",
    "Foundry Automation": "铸造厂自动化",
    "Grid Expansion": "网格扩展",
    "Rainbow Dust": "彩虹魔尘",
    "+0.2x dust yield per level (additive)": "每级+0.2倍魔尘产量（添加剂）",
    "✦ Strong Enchantments:": "✦ 强大的附魔：",
    "Adds an extra row and column to the merge grid.": "向合并网格添加额外的行和列。",
    "All milestones completed!": "已完成所有里程碑！",
    "Also auto-buys dust combat upgrades (Damage and Attack Speed) when you can afford them.": "也自动购买魔尘战斗升级（伤害和攻击速度），当你负担得起他们。",
    "Auto-buy core upgrades (free)": "自动购买核心升级（免费）",
    "Auto-buy enchantments based on ratios and dust combat upgrades": "根据比例和魔尘战斗升级自动购买附魔",
    "Auto-buy foundry slots (free)": "自动购买铸造厂槽位（免费）",
    "Auto-spawn merge gems (free)": "自动生成合并宝石（免费）",
    "Automatically buys energy core upgrades when you can afford them, without spending energy cores.": "自动购买能量核心升级时，你可以负担得起，不消耗能量核心。",
    "Automatically buys new foundry slots when you can afford them, without spending mana.": "自动购买新的铸造槽时，你可以负担他们，不消耗法力。",
    "Automatically purchase enchantments based on the ratios you set for each tier. The overflow option determines which enchantment gets the extra level when ratios don't divide evenly.": "根据你为每层设定的比例自动购买附魔。溢出选项决定了当比例不均匀分配时，哪个附魔获得额外等级。",
    "Automatically spawns merge gems when you can afford them, without spending mana.": "自动生成合并宝石时，你可以支付他们，不消耗法力。",
    "Conversion:": "转换:",
    "Each tier converts at its own ratio: T1 = 2:1, T2 = 4:1, T3 = 8:1, etc.": "每一层按自己的比例转换：T1 = 2:1, T2 = 4:1, T3 = 8:1等。",
    "Instantly converts a percentage of your gem income to dust.": "立即转换你的宝石收入的百分比魔尘。",
    "Mana is no longer capped at 1e21. Gain more SP per singularity based on how far past the cap you go.": "法力不再上限为1e21。每个奇点获得更多的SP取决于你超过上限的距离。",
    "Merge Automation": "合并自动化",
    "No discount for T1": "T1不打折",
    "Overflow": "溢出",
    "Replace pulverizers with instant dust conversion from gem income": "用宝石收益的即时魔尘转换取代粉碎机",
    "SP Boost Milestone": "奇点点数提升里程碑",
    "Strong Enchantments": "强大的附魔",
    "Invalid save data": "无效的存档",
    "Base output/craft": "基础输出/制作",
    "Base cost/craft": "基础成本/制作",
    "Craft": "制作",
    "Crafters:": "工匠:",
    "Buy crafter": "购买工匠",
    "Expeditions": "探险",
    "free": "免费",
    "Output per craft": "输出/每制作",
    "Input per craft": "输入/每制作",
    "Mana gems": "法力宝石",
    "Inventory": "库存",
    "Mana Generation Breakdown": "法力生成明细",
    "Net mana rate": "净法力速率",
    "No gems yet": "暂无宝石",
    "Prestige": "声望",
    "Research": "研究",
    "Tip: right-click crafter buttons to assign/unassign all crafters": "提示：右键点击工匠按钮可对所有工匠进行分配/取消分配操作。",
    "Craft speed": "制作速度",
    "Input per second": "输入/秒",
    "Output per second": "输出/秒",
    "Crafters": "工匠",
    "Research flasks": "研究烧瓶",
    "Buy": "购买",
    "Cheaper Expedition Units": "更便宜的探险单位",
    "Cheaper Gems": "更便宜的宝石",
    "Cheaper Flasks": "更便宜的烧瓶",
    "Crafter's Guild": "工匠公会",
    "Does not affect flask or military output.": "不影响烧瓶或军事产出。",
    "Max 10 levels.": "最多10级。",
    "Multipliers": "乘数",
    "Multiplies ALL gem crafting output by x1.2 per level.": "每级增加所有宝石制作输出x1.2。",
    "Reduces flask crafting input costs by 5% per level (additive).": "每级降低烧瓶制作投入成本5%（附加）。",
    "Reduces gem crafting input costs by 5% per level (additive).": "每级降低5%的宝石制造成本（附加）。",
    "Reduces military crafting input costs by 5% per level (additive).": "每级减少5%的军事制造投入成本（附加）。",
    "Total multiplier = (1 + bonus) ^ min(total crafters, 30).": "总乘数 = (1 + 奖励) ^ 最小（总工匠数量，30）",
    "Applies to gems, flasks, and military.": "适用于宝石，烧瓶，和军事。",
    "At max level, expedition units cost 50% less to craft.": "在最高等级，探险单位的建造成本降低50%。",
    "At max level, flasks cost 50% less to craft.": "在最高等级，烧瓶的制造成本降低50%。",
    "At max level, gems cost 50% less to craft.": "最高等级时，宝石的制作成本降低50%。",
    "No flasks yet": "暂无烧瓶",
    "Flasks": "烧瓶",
    "Expedition Units": "探险单位",
    "(all recipes)": "(所有配方)",
    "Mana Gems": "法力宝石",
    "Recipe": "配方",
    "Recipe bonus:": "配方加成:",
    "recipes per prestige (any recipe)": "配方每声望 (任意配方)",
    "Spend items from a recipe's inventory for permanent output multipliers. Prestige is not reset on tier.": "从配方的库存中花费物品可获得永久性的输出加成。声望不重置层级。",
    "Global bonus:": "全局加成:",
    "Global prestige bonus:": "全局声望加成:",
    "Gem Manufacturing": "宝石制造",
    "Auto": "自动",
    "all": "全部",
    "Does not increase consumption.": "不增加消耗。",
    "Each of the first 30 crafters multiplies ALL crafting output (does not increase consumption).": "前 30 名工匠中的每一位都会使所有制作产出成倍增加（但不会增加消耗量）。",
    "How prestige works": "声望工作原理",
    "▸ Cost scales x100 per prestige (1.00k → 100k → 10.0m → ...)": "▸ 成本缩放 x100 每次声望 (1.00k → 100k → 10.0m → ...)",
    "▸ Each prestige subtracts the requirement from inventory": "▸ 每次提升声望都会从库存中扣除相应数量的物品。",
    "Count": "数量",
    "Research Flasks": "研究烧瓶",
    "About": "关于",
    "Display": "显示",
    "Game": "游戏",
    "Pause Game": "暂停游戏",
    "View Changelog": "查看更新日志",
    "UI Scale": "界面缩放",
    "Off": "关闭",
    "On": "打开",
    "(Current:": "(当前:",
    "• Altar of Sacrifice": "• 祭祀之坛",
    "• Upgrade Auto-Buy": "• 升级自动购买",
    "Bonuses": "加成",
    "Req:": "要求:",
    "Tier Milestones": "层级里程碑",
    "Unlocks": "解锁",
    "Reset your progress to unlock permanent bonuses. Bonuses persist through future resets.": "重置您的进度以获取永久性奖励。奖励会在后续的重置中持续生效。",
    "You must craft expedition units before you can start an expedition": "在开始探险之前，您必须先组建探险队伍。",
    "Cycle Tab Left": "向左循环切换标签页",
    "Cycle Tab Right": "向右循环切换标签页",
    "Rebind": "重新绑定",
    "Resume Game": "返回游戏",
    "Game is paused - time is not accumulating": "游戏已暂停——时间不会累加了",
    "Click Rebind, then press any key to assign it.": "点击“重新绑定”，然后按任意键进行设置。",
    "Swap Realm": "交换领域",
    "All Expeditions": "所有探险",
    "Ancient Ruins": "古代遗迹",
    "Expedition Log": "探险日志",
    "Forest Patrol": "森林巡逻队",
    "Mountain Pass": "山口",
    "No expeditions completed yet.": "暂无完成的探险。",
    "Prime Realm Mastery": "原始领域精通",
    "Realm of War Mastery": "战争领域精通",
    "Shard Affinity": "碎片亲和力",
    "Wraith Stronghold": "幽灵堡垒",
    "Multiplies T1 Knight combat strength by x1.3 per level.": "每升一级，T1 骑士的战斗力量增加 1.3x。",
    "You must get artifact shards from expeditions before you can craft artifacts": "在制作神器之前，您必须通过探险活动获取神器碎片。",
    "On failure": "在失败时",
    "On success": "在成功时",
    "Reduces expedition duration": "缩短探险时间",
    "Reward mult": "奖励乘数",
    "Rewards:": "奖励:",
    "Save and Start": "保存并开始",
    "strength / difficulty": "力量 / 难度",
    "Strength:": "力量:",
    "Success rate": "成功率",
    "Success:": "成功:",
    "Repeat if units available": "如果单位可用可重复",
    "Reward bonus is 2x the difficulty bonus": "奖励加成是难度加成的两倍。",
    "Increases combat strength, improving success rate": "增强战斗力量，提高成功率",
    "Difficulty:": "难度:",
    "Difficulty mult": "难度乘数",
    "Beacons": "灯塔",
    "Beacon Diff:": "灯塔难度:",
    "Army": "军队",
    "base / (1 + speed / 10)": "基础 / (1 + 速度 / 10)",
    "all units lost, rewards granted": "所有单位阵亡，奖励已发放。",
    "all units lost, no rewards": "全军覆没，无奖励",
    "Duration": "持续时长",
    "Duration:": "持续时长:",
    "Fleet": "队伍",
    "Formula": "公式",
    "Higher fleet value = faster expeditions": "队伍值越高，探险越快",
    "Increases rewards (2x) and difficulty (1x)": "提高奖励（2x）和难度（1x）",
    "Capped at 100%": "上限为100%",
    "Beacon Reward:": "灯塔奖励:",
    "Chance": "几率",
    "Time": "时间",
    "Rewards": "奖励",
    "SHRD": "碎片",
    "Expeditions Loot": "探险战利品",
    "Expedition": "探险",
    "Artifact": "神器",
    "Artifact Shards:": "神器碎片:",
    "Combat Artifact": "战斗神器",
    "combat strength": "战斗力量",
    "Craft and upgrade artifacts with artifact shards from expeditions.": "利用探险活动获得的神器碎片来打造和升级神器。",
    "craft speed": "制作速度",
    "Crafting Speed": "制作速度",
    "Forge": "锻造",
    "gem output": "宝石输出",
    "General": "常规",
    "Rings": "戒指",
    "Active Bonuses": "活跃加成",
    "+Nullstones": "+空石",
    "Artifact output": "神器输出",
    "Artifact Shard": "神器碎片",
    "Expedition Rewards": "探险奖励",
    "Copied to clipboard!": "已复制到剪贴板！",
    "Altar": "祭坛",
    "Sacrifice bonus": "牺牲加成",
    "✓ Complete": "✓ 完成",
    "Resets BOTH realms": "重置两个领域",
    "T2 reset requires Realm of War. Advance through expeditions to unlock the Realm tab and open a portal to the Realm of War.": "T2 重置需要“战争领域”。通过探险任务前进，以解锁“领域”选项卡并打开通往“战争领域”的传送门。",
    "• Auto-Prestige": "• 自动声望",
    "• Heroic Expeditions": "• 英雄探险",
    "Altar of Sacrifice": "祭坛",
    "Bonus": "加成",
    "Flask": "烧瓶",
    "Nullstone": "空石",
    "Owned": "拥有",
    "Sacrifice": "牺牲",
    "Unit": "单位",
    "Sacrificed": "已牺牲",
    "Sacrifice items to permanently increase their output bonus.": "将物品进行牺牲处理，以永久性地提高其输出加成效果。",
    "Stop": "停止",
    "• Artifacts persist on reset": "• 重置后神器会继续存在",
    "Click to switch to the Realm of War.": "点击以切换到战争领域。",
    "Prime Realm": "原始领域",
    "Realm": "领域",
    "Hide maxed upgrades": "隐藏满级升级",
    "Multiplies T4 Knight combat strength by x1.3 per level.": "每级增加T4骑士的战斗力量 ×1.3。",
    "Available": "可用",
    "A harsher realm with unique mechanics:": "一个更具挑战性的领域，拥有独特的机制：",
    "Cannot craft": "无法制作",
    "Click to enter": "点击进入",
    "Click to switch to Prime Realm.": "单击以切换到原始领域。",
    "Craftable": "可制作",
    "Current realm": "当前领域",
    "Flask gem costs": "烧瓶宝石成本",
    "Harness the power of nullstone to open a gateway to another realm.": "利用空石的力量，开启通往另一个世界的通道。",
    "Heroic expeditions": "英雄探险",
    "Mana generation": "法力生成",
    "Military": "军事",
    "Normal": "普通",
    "Penalties": "惩罚",
    "Quest unlock": "任务解锁",
    "Quest bonuses": "任务加成",
    "Realm of War": "战争领域",
    "Realm Portal": "领域传送门",
    "Sacrifice batch": "批量牺牲",
    "Sacrifice cap": "牺牲上限",
    "Sacrifice scaling": "牺牲缩放",
    "Square rooted": "平方根",
    "T1-T4 Swords": "T1-T4 剑",
    "The standard realm with normal mechanics.": "具有常规机制的标准领域。",
    "Tier output multipliers": "层级输出乘数",
    "Unique": "独特",
    "T2 reset requires Realm of War. Switch realms to perform the reset.": "T2重置需要战争领域。切换至相应领域以执行重置操作。",
    "In the Realm of War, you cannot craft artifacts - only receive shipments from the Prime Realm.": "在战争领域，您无法制作神器——只能从主领域接收货物。",
    "Ship": "装船",
    "Ship Artifacts to Realm of War": "运送神器到战争领域",
    "Shipped artifacts are removed from the Prime Realm and must be re-crafted.\n        You can overwrite a Realm of War artifact only if the Prime Realm version has a higher upgrade level.": "已发货的物品将从主领域中取出，并且必须重新制作。\n        只有当主领域的版本具有更高的升级等级时，您才能覆盖战争领域的物品。",
    "No artifacts shipped yet. Use the Realm tab to ship artifacts from the Prime Realm.": "目前尚未有神器发货。请使用“领域”选项卡从主领域中发货神器。",
    "Click to switch realm.": "点击以切换领域。",
    "Main": "首页",
    "Expedition Loot": "探险战利品",
    "Tip: click the Auto header to toggle all automations": "提示：点击“自动”标题即可切换所有自动化设置。",
    "Open Portal to Realm of Magic": "打开前往魔法领域的传送门",
    "Requires:": "要求:",
    "Forge Enhancer": "锻造强化器",
    "Forge -": "锻造 -",
    "Flask recipe mult": "烧瓶配方乘数",
    "Doubles arcane soul production in the Realm of Magic": "在魔法领域大幅提升灵魂的生成量",
    "Quest bonus": "任务加成",
    "Sword Efficiency": "剑的效率",
    "• T4+ Swords usable in Prime Realm": "• T4+ 剑可以在原始领域使用",
    "Artifacts shipped from the Prime Realm.": "从原始领域运来的神器。",
    "Output Bonuses": "输出加成",
    "Quest Output Bonuses": "任务输出加成",
    "All research upgrades maxed.": "所有研究升级已达到上限。",
    "Tip: click the Auto header to toggle all automations in that section": "提示：点击“自动”标题即可切换该部分的所有自动化设置。",
    "Arcane Soul": "奥术灵魂",
    "Arcane Soul Production Breakdown": "奥术灵魂生产细分",
    "Cost escalation": "成本逐步上升",
    "Creature": "生物",
    "Magical Creatures": "魔法生物",
    "Net soul rate": "净灵魂速率",
    "PIXI": "小精灵",
    "Pixie": "小精灵",
    "Production": "生产",
    "Produces": "产出",
    "Produces Arcane Souls passively. Crafted in the Prime Realm from T8 gems.": "被动产生奥术灵魂。由T8宝石在原始领域中制作。",
    "Progress": "进度",
    "Realm of Magic": "魔法领域",
    "SOUL": "灵魂",
    "Soul Mastery": "灵魂精通",
    "Soulforge": "灵魂锻造",
    "Creature Mastery": "生物精通",
    "Forest": "森林",
    "Heroic": "英雄",
    "Heroic expeditions never reset.": "英雄探险永不重置。",
    "Mine": "矿山",
    "Realm Mastery": "领域精通",
    "• Arcane soul production x1.2 per victory (compounding)": "• 每胜利一次，爱书灵魂产出增加 1.2x（累加）",
    "• Difficulty scales x10 per victory": "• 每取得一次胜利，难度系数将增加 10x。",
    "Equip Diff:": "装备难度:",
    "Equip Reward:": "装备奖励:",
    "Equipment": "装备",
    "• Creature production x1.2 per victory (compounding)": "• 每场胜利的生物产量 x1.2（累加）",
    "• R1 + R2 gem production x1.2 per victory (compounding)": "• 每场胜利使 领域1 + 领域2宝石产量 x1.2（累加）",
    "A magical realm powered by arcane souls.": "一个由奥术灵魂驱动的魔法王国。",
    "About Ascension": "关于转生",
    "Anything outside Realm of Magic": "任何超出魔法领域的事物",
    "Arcane buildings": "奥术建筑",
    "Arcane Soul Production": "奥术灵魂生产",
    "Arcane Souls": "奥术灵魂",
    "Arcane Wonders": "奥术奇迹",
    "Ascend (not enough pixies)": "转生 (小精灵不足)",
    "Ascended Souls which can be used to buy Ascended upgrades.": "可以用来购买转生升级的转生灵魂。",
    "Ascended upgrades": "转生升级",
    "Ascension does not reset:": "转生不会重置:",
    "Ascension grants": "转生授予",
    "Ascension resets:": "转生重置:",
    "Bigger Dwelling": "更大的住宅",
    "Creatures": "生物",
    "Each arcane dwelling provides additional population": "每个奥术住所都提供额外的人口",
    "Expedition equipment": "探险装备",
    "Expedition loot": "探险战利品",
    "Forge Enhancers": "锻造强化",
    "gain is based on pixies produced this ascension. The formula is (pixies/100k)^0.5": "收益是基于此次升空所产生的小精灵数量计算得出的。计算公式为：（小精灵/100000）^0.5",
    "Increases arcane soul production": "提高奥术灵魂生产",
    "Generate arcane souls": "生成奥术灵魂",
    "Increases creature production speed": "提高生物生成速度",
    "Increases pixie combat strength": "提高小精灵的战斗力量",
    "Multiplies T8 gem production in Realm 1 and Realm 2": "增加领域1和领域2的T8宝石产量",
    "Pixie Strength": "小精灵力量",
    "Production Speed": "生产速度",
    "Recipes": "配方",
    "Soulforges": "灵魂锻造",
    "T8 Gem Production (R1+R2)": "T8 宝石生产 (领域1+领域2)",
    "Require arcane souls": "需要奥术灵魂",
    "Heroic mastery": "英雄精通",
    "Forges arcane souls in the Realm of Magic": "在魔法领域中锻造奥术灵魂",
    "ANIM": "灵魂",
    "Anima Core": "灵魂核心",
    "Arcane Warden": "奥术守望者",
    "Arcane Well": "奥术之井",
    "AXE": "斧子",
    "BAR": "锭",
    "EIDO": "幻影",
    "Eidolon": "幻影",
    "Expedition Equipment": "探险装备",
    "LOG": "原木",
    "Luminary": "明星",
    "LUMI": "明星",
    "Mana Wisp": "法力浮灵",
    "MANA": "法力",
    "PICK": "镐子",
    "Village": "村庄",
    "WARD": "沃德",
    "Multiplies Arcane Soul output by 1 + count. Crafted in the Realm of War from T8 gems.": "奥术灵魂输出乘以1 +计数。在战争领域由T8宝石制作。",
    "Multiplies Arcane Soul output by x1.3 per ascension level.": "每升一级增加1 ×1.3 奥术灵魂输出。",
    "Multiplies Arcane Soul output by x1.2 per Soul Mastery heroic victory.": "每个灵魂精通英雄胜利使奥术灵魂输出增加 x1.2。",
    "Multiplies Arcane Soul output by x1.25 per building. Built in the Village tab.": "每座建筑的奥术灵魂输出乘以x1.25。此功能位于“村庄”选项卡中。",
    "Axe": "斧子",
    "Pickaxe": "镐子",
    "Arcane Sanctum": "奥术密室",
    "Arcane Dwelling": "奥术住宅",
    "Arcane Buildings": "奥术建筑",
    "Building": "建筑",
    "creature prod": "生物产出",
    "Enchanting Tower": "魔塔",
    "soul prod": "灵魂产出",
    "gem prod": "宝石产出",
    "Population:": "人口:",
    "Rate": "速率",
    "Wonder": "奇迹",
    "Workers": "工人",
    "Workshop": "作坊",
    "Provides 1 population per building. Population is used to assign workers in the Workshop and Arcane Wonders.": "每个建筑提供 1 个人口。人口是用来分配到作坊和奥术奇迹的工人。",
    "Multiplies Arcane Soul production by x1.25 per building.": "每座建筑会使奥术灵魂的产出增加 x1.25。",
    "Tip: arcane wonder progress and completions do not reset on ascension": "提示：奥术奇迹的进度和完成度不会在转生时重置",
    "Assigned to Mine expeditions. Increases both rewards and difficulty.": "被分配到矿井探险任务中。这会同时提升奖励和增加难度。",
    "Assigned to Forest expeditions. Increases both rewards and difficulty.": "被分配到森林探险任务中。这会同时提升奖励和增加难度。",
    "Multiplies all creature passive production by x2 per level. Built by assigning population. Persists through ascension.": "每升一级，所有生物的被动产出都会乘以 x2。通过分配人口来建造。在转生过程中持续生效。",
    "Multiplies all gem production in R1 and R2 by x2 per level. Built by assigning population. Persists through ascension.": "每级将领域1和领域2中的所有宝石产量乘以x2。通过分配人口来建造。在转生过程中会持续生效。",
    "• Research Auto-Buy": "• 研究自动购买",
    "Realm of Magic Heroic": "魔法领域英雄",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "NULS": "空石",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "×": "×",
    "=": "=",
    "▶": "▶",
    "—": "—",
    "🔒 ???": "🔒 ???",
    "→": "→",
    "⚠ T": "⚠ T",
    "✓": "✓",
    "• +": "• +",
    "• ×": "• ×",
    "○": "○",
    "🔒": "🔒",
    "•": "•",
    "%": "%",
    "^": "^",
    "→ x": "→ x",
    "−": "−",
    "✔": "✔",
    "?": "?",
    "▸": "▸",
    "--": "--",
    "☑": "☑",
    "☐": "☐",
    "": "",
    "": "",
    "": "",
    "": "",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': '',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Cost: ": "成本: ",
    "• Base drop rate: ": "• 基础掉率: ",
    "Tab Highlighting ": "标签高亮 ",
    "Background Image ": "背景图片 ",
    "Version ": "版本 ",
    "Up to x": "最多 x",
    "Owned: ": "拥有: ",
    "In R2: +": "在 领域2: +",
    "Creatures x": "生物 x",
    "Souls x": "灵魂 x",
    "W: ": "胜利: ",
    "Already in ": "已经在 ",
    "Shards x": "碎片 x",
    "Ascend +": "转生 +",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " mana": " 法力",
    " cores": " 核心",
    " skipped)": " 已跳过)",
    " mana\n            ": " 法力\n            ",
    " Crafter Speed (total)": "工匠速度 (总计)",
    "+ Swords usable in any realm": "+ 剑可以在任何领域使用",
    " effect)": " 效果)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^• x([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^\(([\d\.]+)m\)$/,
    /^\(([\d\.]+)k\)$/,
    /^\-([\d\.]+)k\/s$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^n\^([\d\.]+) × ([\d\.]+)$/,
    /^([\d\.]+)t$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)k$/,
    /^\(([\d\.]+)k\)$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)b$/,
    /^([\d\.]+)qa$/,
    /^([\d\.]+)qi$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\-([\d\.,]+)s$/,
    /^\/([\d\.,]+)\)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^T([\d\.,]+)$/,
    /^([\d\.,]+), T([\d\.,]+)$/,
    /^([\d\.,]+), T([\d\.,]+), T([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^\=([\d\.]+)e([\d\.,]+)\/s$/,
    /^\√([\d\.]+)e([\d\.,]+) \(R2$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Difficulty: (.+) \+ count(.+)$/, '难度: $1 + 数量$2'],
    [/^Reward: (.+) \+ count(.+)$/, '奖励: $1 + 数量$2'],
    [/^(.+) \— Craft (.+) Pixies \($/, '$1 — 制作 $2 小精灵 ('],
    [/^At max level, (.+) Swords cost (.+) less to craft.$/, '在最高等级时，$1 剑的制作成本降低 $2。'],
    [/^Reduces (.+) Sword crafting input costs by (.+) per level \(additive\).$/, '每级降低 $1 剑制造的输入成本 $2（附加）。'],
    [/^Altar bonuses do not reset on tier up. Cap: (.+) sacrificed \(x(.+) max\). Sacrifices (.+) items at a time.$/, '祭坛的奖励不会随着等级提升而重置。上限：牺牲 $1（最多可达到 $2x）。每次可牺牲 $3 件物品。'],
    [/^Altar bonuses do not reset on tier up. Cap: (.+) sacrificed \(x(.+) max\).$/, '祭坛的加成效果不会随着等级提升而重置。上限：牺牲物品数量最多可达 $1（最多 x$2）。'],
    [/^\| Duration: (.+)m (.+)s\n                \| Done: (.+)$/, '| 持续时长: $1分 $2秒\n                | 完成: $3'],
    [/^\| Duration: (.+)h (.+)m\n                \| Done: (.+)$/, '| 持续时长: $1小时 $2分钟\n                | 完成: $3'],
    [/^Lv(.+): x(.+) per crafter, \+(.+) per additional level.$/, '等级 $1: x$2 每个工匠, +$3 每个附加等级.'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+)e([\d\.,]+) mana in R([\d\.,]+)$/, '$1e$2 法力在 R$3'],
    [/^Generates ([\d\.]+) mana\/sec$/, '生产 $1 法力/秒'],
    [/^All scale ([\d\.]+)x per level$/, '所有比例为每级 $1x'],
    [/^R([\d\.]+)\+R([\d\.]+) gems x([\d\.]+)$/, 'R$1+R$2 宝石 x$3'],
    [/^([\d\.]+) Arcane Well$/, '$1 奥术之井'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^x([\d\.]+) higher$/, 'x$1 更高'],
    [/^x([\d\.]+) slower$/, 'x$1 更低'],
    [/^• x([\d\.]+) Crafter Speed$/, '• x$1 工匠速度'],
    [/^\+x([\d\.]+) output multiplier for$/, '+x$1 输出乘数到'],
    [/^\+x([\d\.]+) output multiplier for that recipe per prestige$/, '+x$1 输出乘数到该配方每次声望'],
    [/^→ x([\d\.]+) multiplier$/, '→ x$1 乘数'],
    [/^→ x([\d\.]+)(.+) multiplier$/, '→ x$1$2 乘数'],
    [/^to unlock \(([\d\.]+) more\)$/, '以解锁 (还需要 $1)'],
    [/^to unlock \(([\d\.]+)(.+) more\)$/, '以解锁 (还需要 $1$2)'],
    [/^([\d\.]+) T([\d\.]+) gems$/, '$1 T$2 宝石'],
    [/^([\d\.]+)(.+) T([\d\.]+) gems$/, '$1$2 T$3 宝石'],
    [/^([\d\.]+) T([\d\.]+) gems × ([\d\.]+)\/s$/, '$1 T$2 宝石 × $3/秒'],
    [/^([\d\.]+)(.+) T([\d\.]+) gems × ([\d\.]+)\/s$/, '$1$2 T$3 宝石 × $4/秒'],
    [/^([\d\.]+)x enchantment power per level$/, '每级 $1x 附魔力量'],
    [/^([\d\.]+)x SP earned per level$/, '每级 $1x 赚取的奇点点数'],
    [/^([\d\.]+)x craft speed$/, '$1x 制作速度'],
    [/^([\d\.]+)x global crafting speed$/, '$1x 全局制作速度'],
    [/^([\d\.]+)x T([\d\.]+) speed, ([\d\.]+)x yield per level$/, '$1x T$2 速度, $3x 产量每级'],
    [/^([\d\.]+) HP\/s regen, ([\d\.]+)x HP, ([\d\.]+)x attack speed$/, '$1 生命值/秒 回复, $2x 生命值, $3x 攻击速度'],
    [/^([\d\.]+) HP\/s regen, ([\d\.]+)x HP, ([\d\.]+)x attack speed, ([\d\.]+)x damage$/, '$1 生命值/秒 回复, $2x 生命值, $3x 攻击速度, $4x 伤害'],
    [/^×([\d\.]+) global \(([\d\.]+)x\)$/, '×$1 全局 ($2x)'],
    [/^×([\d\.]+) damage \(([\d\.]+)x\)$/, '×$1 伤害 ($2x)'],
    [/^×([\d\.]+) HP \(([\d\.]+)x\)$/, '×$1 生命值 ($2x)'],
    [/^×([\d\.]+) Damage \(([\d\.]+)x\)$/, '×$1 伤害 ($2x)'],
    [/^×([\d\.]+) attack speed \(([\d\.]+)x\)$/, '×$1 攻击速度 ($2x)'],
    [/^×([\d\.]+) Speed \(([\d\.]+)x\)$/, '×$1 速度 ($2x)'],
    [/^×([\d\.]+) mana \(([\d\.]+)x\)$/, '×$1 法力 ($2x)'],
    [/^([\d\.]+)x speed, ([\d\.]+)x yield for T([\d\.]+)\-T([\d\.]+)$/, '$1x 速度, $2x 生产 对于 T$3-T$4'],
    [/^\+([\d\.]+) slot \(\+([\d\.]+) total\)$/, '+$1 槽位 (+$2 总计)'],
    [/^\-([\d\.]+)s revive \(([\d\.]+)s\)$/, '-$1 秒 复活 ($2秒)'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\(([\d\.]+)\/s\)$/, '($1/秒)'],
    [/^\(([\d\.]+)(.+)\/s\)$/, '($1$2/秒)'],
    [/^\(\-([\d\.]+)\/s\)$/, '(-$1/秒)'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1/秒)'],
    [/^\(\+([\d\.]+)(.+)\/s\)$/, '(+$1$2/秒)'],
    [/^([\d\.]+)(.+) soulforge × ([\d\.]+)\/s$/, '$1$2 灵魂锻造 x $3/秒'],
    [/^(.+) soulforges × ([\d\.]+)\/s$/, '$1 灵魂锻造 x $2/秒'],
    [/^([\d\.]+)(.+)\/s$/, '$1$2/秒'],
    [/^x([\d\.]+) per craft$/, 'x$1 每次制作'],
    [/^x([\d\.]+) multiplier$/, 'x$1 乘数'],
    [/^x([\d\.]+)(.+)$/, 'x$1$2'],
    [/^\+([\d\.]+)\% global speed per level$/, '每级 +$1% 全局速度'],
    [/^\+([\d\.]+)\% global yield per level$/, '每级 +$1% 全局生产'],
    [/^\+([\d\.]+)\% energy core drops per level$/, '每级 +$1% 能量和谐掉落'],
    [/^\+([\d\.]+)\% prism effectiveness per level$/, '每级 +$1% 棱镜效果'],
    [/^\+([\d\.]+)\% artifact effectiveness per level$/, '每级 +$1% 神器效果'],
    [/^\+([\d\.]+)\% singularity points per level$/, '每级 +$1% 奇点点数'],
    [/^\+([\d\.]+)\% base$/, '+$1% 基础'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)\% to Ascension$/, '$1% 转生进度'],
    [/^\+([\d\.]+)\% mana multiplier$/, '+$1% 法力乘数'],
    [/^\+([\d\.]+)\/s$/, '+$1/秒'],
    [/^\=([\d\.]+)\/s$/, '=$1/秒'],
    [/^\+([\d\.]+)\/hr$/, '+$1/小时'],
    [/^\-([\d\.]+)\/hr$/, '-$1/小时'],
    [/^\-([\d\.]+)\/s$/, '-$1/秒'],
    [/^([\d\.]+)k\/s$/, '$1k/秒'],
    [/^\+([\d\.]+)k\/s$/, '+$1k/秒'],
    [/^\+([\d\.]+)b\/s$/, '+$1b/秒'],
    [/^\+([\d\.]+)t\/s$/, '+$1t/秒'],
    [/^\+([\d\.]+)qa\/s$/, '+$1qa/秒'],
    [/^\-([\d\.]+)k\/s$/, '-$1k/秒'],
    [/^\-([\d\.]+)m\/s$/, '-$1m/秒'],
    [/^\+([\d\.]+)(.+)\/s$/, '+$1$2/秒'],
    [/^\-([\d\.]+)b\/s$/, '-$1b/秒'],
    [/^\+([\d\.]+)\/min$/, '+$1/分钟'],
    [/^\-([\d\.]+)\/min$/, '-$1/分钟'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)d ([\d\.]+)h$/, '$1天 $2小时'],
    [/^([\d\.]+)e([\d\.,]+) Arcane Well$/, '$1e$2 奥术之井'],
    [/^([\d\.]+)e([\d\.,]+) Forge Enhancers$/, '$1e$2 锻造强化'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.]+)e([\d\.,]+) mana in R2\n            $/, '$1e$2 法力在 领域2\n            '],
    [/^\+([\d\.,]+) merge grid size$/, '+$1 合并网格尺寸'],
    [/^\+([\d\.,]+)min$/, '+$1 分钟'],
    [/^\+([\d\.,]+) population$/, '+$1 人口'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^([\d\.,]+)h ([\d\.,]+)m \(([\d\.,]+)h ([\d\.,]+)m$/, '$1小时 $2分钟 ($3小时 $4分钟'],
    [/^([\d\.,]+) \+ taunt \/ ([\d\.,]+)$/, '$1 + 嘲讽 / $2'],
    [/^([\d\.,]+)s ago$/, '$1 秒前'],
    [/^\-([\d\.,]+)s ago$/, '-$1 秒前'],
    [/^([\d\.,]+)m ago$/, '$1 分钟前'],
    [/^([\d\.,]+)h ago$/, '$1 小时前'],
    [/^([\d\.,]+) more$/, '还需 $1'],
    [/^([\d\.,]+) tiers$/, '$1 层级'],
    [/^([\d\.,]+) completions$/, '$1 完成'],
    [/^([\d\.,]+) per artifact$/, '$1 每个神器'],
    [/^([\d\.,]+) Arcane Soul \/ ([\d\.,]+)s$/, '$1 奥术灵魂 / $2秒'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) at once$/, '一次 $1'],
    [/^T([\d\.,]+) Flask$/, 'T$1 烧瓶'],
    [/^T([\d\.,]+) Shield$/, 'T$1 盾牌'],
    [/^T([\d\.,]+)-T([\d\.,]+) Automation$/, 'T$1-T$2 自动化'],
    [/^Automatically buys Speed and Yield upgrades for T([\d\.,]+) and T([\d\.,]+) gems when you can afford them, without spending mana.$/, '在你买得起的情况下，自动为T$1和T$2宝石购买速度和产量升级，而不需要消耗法力值。'],
    [/^T([\d\.,]+) Knight$/, 'T$1 骑士'],
    [/^T([\d\.,]+) Mana Gem$/, 'T$1 法力宝石'],
    [/^Prestige \(([\d\.,]+)\)$/, '声望 ($1)'],
    [/^Shard ([\d\.,]+)$/, '碎片 $1'],
    [/^Max ([\d\.,]+) levels.$/, '最大 $1 级.'],
    [/^Research \(([\d\.,]+)\)$/, '研究 ($1)'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Lv.([\d\.,]+)$/, '等级 $1'],
    [/^T([\d\.,]+) Mastery: \+$/, 'T$1 精通: +'],
    [/^T([\d\.,]+) Lv([\d\.,]+)$/, 'T$1 等级 $2'],
    [/^T([\d\.,]+) Mastery \(Lv$/, 'T$1 (等级'],
    [/^T([\d\.,]+) Knight Strength$/, 'T$1 骑士力量'],
    [/^T([\d\.,]+) Boat$/, 'T$1 船只'],
    [/^T([\d\.,]+) combat$/, 'T$1 战斗'],
    [/^T([\d\.,]+) crafting_speed$/, 'T$1 制作速度'],
    [/^Cheaper T([\d\.,]+) Swords$/, '更便宜的 T$1 剑'],
    [/^Ascension: T([\d\.,]+) Gem$/, '转生: T$1 宝石'],
    [/^T([\d\.,]+) Sword$/, 'T$1 剑'],
    [/^T([\d\.,]+) ring$/, 'T$1 戒指'],
    [/^T([\d\.,]+) Quest$/, 'T$1 任务'],
    [/^T([\d\.,]+) Ring$/, 'T$1 戒指'],
    [/^T([\d\.,]+) Beacon$/, 'T$1 灯塔'],
    [/^T([\d\.,]+) Prism$/, 'T$1 棱镜'],
    [/^T([\d\.,]+) Mastery$/, 'T$1 精通'],
    [/^T([\d\.,]+) Output \(\+(.+)\)$/, 'T$1 输出 (+$2)'],
    [/^T([\d\.,]+)\-T([\d\.,]+) Output \(\+(.+)\)$/, 'T$1-T$2 输出 (+$3)'],
    [/^T([\d\.,]+)\-T([\d\.,]+) Output$/, 'T$1-T$2 输出'],
    [/^T([\d\.,]+)\-T([\d\.,]+) Quest$/, 'T$1-T$2 任务'],
    [/^T([\d\.,]+)\-T([\d\.,]+) Swords$/, 'T$1-T$2 剑'],
    [/^Crush T([\d\.,]+) Gem$/, '粉碎 T$1 宝石'],
    [/^Crush T([\d\.,]+) gems into T([\d\.,]+) dust$/, '粉碎 T$1 宝石 为 T$2 魔尘'],
    [/^Auto-buy T([\d\.,]+) \& T([\d\.,]+) upgrades \(free\)$/, '自动购买 T$1 和 T$2 升级（免费）'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^(.+) \/ (.+) Soulforge$/, '$1 \/ $2 灵魂锻造'],
    [/^(.+) \/ (.+) Nullstone$/, '$1 \/ $2 空石'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);